// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxH3OMDSuRczqLYoxI9JYCu4dv35XGvFY',
    appId: '1:205157815770:web:f2b8e8d404de24bc2c1ce3',
    messagingSenderId: '205157815770',
    projectId: 'base-63161',
    authDomain: 'base-63161.firebaseapp.com',
    storageBucket: 'base-63161.firebasestorage.app',
    measurementId: 'G-4YSK50XN1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZWhaQR0CstKK1xxpA3QrKDO-yg1yMYeo',
    appId: '1:205157815770:android:63d26aaf4bfd64032c1ce3',
    messagingSenderId: '205157815770',
    projectId: 'base-63161',
    storageBucket: 'base-63161.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApnT9EHGAlFweTlNQwHOHU9ihefJ45Hls',
    appId: '1:205157815770:ios:3059f233dbd0c2af2c1ce3',
    messagingSenderId: '205157815770',
    projectId: 'base-63161',
    storageBucket: 'base-63161.firebasestorage.app',
    iosBundleId: 'com.example.homework2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApnT9EHGAlFweTlNQwHOHU9ihefJ45Hls',
    appId: '1:205157815770:ios:3059f233dbd0c2af2c1ce3',
    messagingSenderId: '205157815770',
    projectId: 'base-63161',
    storageBucket: 'base-63161.firebasestorage.app',
    iosBundleId: 'com.example.homework2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxH3OMDSuRczqLYoxI9JYCu4dv35XGvFY',
    appId: '1:205157815770:web:248decad2cb752f42c1ce3',
    messagingSenderId: '205157815770',
    projectId: 'base-63161',
    authDomain: 'base-63161.firebaseapp.com',
    storageBucket: 'base-63161.firebasestorage.app',
    measurementId: 'G-YSK5C89PJG',
  );
}
